sonar.projectKey=sunshinetoyou_BoanCurator
sonar.organization=danyeon-goqudeo2

sonar.sources=BE
sonar.exclusions=BE/.venv/**,BE/__pycache__/**,BE/tests/**,BE/chroma_data/**,BE/postgres_data/**
sonar.python.version=3.11
